"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.OtpEmail = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const components_1 = require("@react-email/components");
const OtpEmail = ({ userEmail, otpCode }) => {
    return ((0, jsx_runtime_1.jsxs)(components_1.Html, { children: [(0, jsx_runtime_1.jsx)(components_1.Head, {}), (0, jsx_runtime_1.jsx)(components_1.Tailwind, { children: (0, jsx_runtime_1.jsx)(components_1.Body, { className: "bg-white my-auto mx-auto font-sans", children: (0, jsx_runtime_1.jsxs)(components_1.Container, { className: "border border-solid border-[#eaeaea] rounded my-[40px] mx-auto p-[20px] w-[465px]", children: [(0, jsx_runtime_1.jsx)(components_1.Section, { className: "mt-[20px] text-center", children: (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-2xl font-bold text-gray-900 mt-4 mb-2", children: "Inventory Insights" }) }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: "text-black text-[14px] leading-[24px]", children: ["Hello ", (0, jsx_runtime_1.jsx)("strong", { className: "font-semibold", children: userEmail }), ","] }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-black text-[14px] leading-[24px]", children: "Thank you for trying out Inventory Insights." }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-black text-[14px] leading-[24px]", children: "Use the following One-Time Password (OTP) to complete your login:" }), (0, jsx_runtime_1.jsxs)(components_1.Section, { className: "text-center my-[20px]", children: [(0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-4xl font-bold text-indigo-600 tracking-[0.25em] m-0", children: otpCode }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-xs text-gray-500 mt-2", children: "This OTP is valid for 10 minutes." })] }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-black text-[14px] leading-[24px]", children: "If you did not request this OTP, please ignore this email." }), (0, jsx_runtime_1.jsx)(components_1.Hr, { className: "border border-solid border-[#eaeaea] my-[26px] mx-0 w-full" }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-[#666666] text-[12px] leading-[24px]", children: "This email was sent from Inventory Insights." })] }) }) })] }));
};
exports.OtpEmail = OtpEmail;
exports.default = exports.OtpEmail;
