"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.WelcomeEmail = void 0;
const jsx_runtime_1 = require("react/jsx-runtime");
const components_1 = require("@react-email/components");
const WelcomeEmail = ({ userEmail }) => {
    return ((0, jsx_runtime_1.jsxs)(components_1.Html, { children: [(0, jsx_runtime_1.jsx)(components_1.Head, {}), (0, jsx_runtime_1.jsx)(components_1.Tailwind, { children: (0, jsx_runtime_1.jsx)(components_1.Body, { className: "bg-white my-auto mx-auto font-sans", children: (0, jsx_runtime_1.jsxs)(components_1.Container, { className: "border border-solid border-[#eaeaea] rounded my-[40px] mx-auto p-[20px] w-[465px]", children: [(0, jsx_runtime_1.jsx)(components_1.Section, { className: "mt-[20px] text-center", children: (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-2xl font-bold text-gray-900 mt-4 mb-2", children: "Insightory" }) }), (0, jsx_runtime_1.jsxs)(components_1.Text, { className: "text-black text-[14px] leading-[24px]", children: ["Hello ", (0, jsx_runtime_1.jsx)("strong", { className: "font-semibold", children: userEmail }), ","] }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-black text-[14px] leading-[24px]", children: "Welcome to Insightory! Your email has been successfully verified." }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-black text-[14px] leading-[24px]", children: "We're excited to help you gain valuable insights into your product inventory." }), (0, jsx_runtime_1.jsx)(components_1.Section, { className: "text-center my-[20px]", children: (0, jsx_runtime_1.jsx)(components_1.Button, { href: "http://localhost:3000/dashboard/overview" // Adjust to your deployed dashboard URL
                                    , className: "bg-indigo-600 text-white rounded px-5 py-3 text-[12px] font-semibold no-underline", children: "Go to Dashboard" }) }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-black text-[14px] leading-[24px]", children: "If you have any questions, feel free to reach out to our support team." }), (0, jsx_runtime_1.jsx)(components_1.Hr, { className: "border border-solid border-[#eaeaea] my-[26px] mx-0 w-full" }), (0, jsx_runtime_1.jsx)(components_1.Text, { className: "text-[#666666] text-[12px] leading-[24px]", children: "This email was sent from Insightory." })] }) }) })] }));
};
exports.WelcomeEmail = WelcomeEmail;
exports.default = exports.WelcomeEmail;
